spring.application.name=Tecprog2
spring.datasource.url=jdbc:postgresql://localhost/db_fatecPedroEdLumine
spring.datasource.username=fatec
spring.datasource.password=fatec777
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update